% script to define all used uicontrols and read out their values 
% Usage: run(InputDialog.m)
% Output: a collection of sliders to change the value of signal related variables

% Author: A.Decker, A.Morgenstern, S. Pape
% (c) A.Decker, A. Morgenster, S. Pape Jade Hochschule 
% applied licence see LICENCE.md

%% Global variables
% variables are set global to use them in Wavefunction.m

global figure1
global freqA
global freqB
global amplA
global amplB
global phaseA
global phaseB

global t
global statusT

%% GUI for slider, setting frequency of source A

txtSliderFreqA = uicontrol('Parent',figure1,...
           'Style','text',...
           'Position',[40 580 210  20],...
           'units','normalized', ...
           'String','Frequency "Right":');
       
sliderFreqA = uicontrol('Parent',figure1,...
           'Style','slider',...
           'Position',[25 555 240 20],...
           'units','normalized', ...
           'Value', freqA, ...
           'Min',3,'Max',30, ...
           'Value',15, ...
           'SliderStep',[0.1 0.5],...
            'Tag','SfreqA',...
           'Callback',@sliderCallback);
      
       
%% GUI for slider, setting frequency of source B 

txtSliderFreqB = uicontrol('Parent',figure1,...
           'Style','text',...
           'Position',[40 490 210 20],...
           'units','normalized', ...
           'String','Frequency "Left":');
       
sliderFreqB = uicontrol('Parent',figure1,...
           'Style','slider',...
           'Position',[25 465 240 20],...
           'units','normalized', ...
           'Value', freqB, ...
           'Min',3,'Max',30, ...
           'Value',15, ...
           'SliderStep',[0.1 0.5],...
           'Tag','SfreqB',...
           'Callback',@sliderCallback);
       
%% GUI for slider, setting amplitude of source A 
    
txtSliderAmplA = uicontrol('Parent',figure1,...
           'Style','text',...
           'Position',[40 400 210 20],...
           'units','normalized', ...
           'String','Amplitude "Right":');
       
sliderAmplA = uicontrol('Parent',figure1,...
           'Style','slider',...
           'Position',[25 375 240 20],...
           'units','normalized', ...
           'Value', amplA, ...
           'Min',0.1,'Max',1, ...
           'Value',1, ...
           'SliderStep',[0.05 0.1],....
           'Tag','SamplA',...
           'Callback',@sliderCallback);

%% GUI for slider, setting amplitude of source B 

txtSliderAmplB = uicontrol('Parent',figure1,...
           'Style','text',...
           'Position',[40 310 210 20],...
           'units','normalized', ...
           'String','Amplitude "Left":');
       
sliderAmplB = uicontrol('Parent',figure1,...
           'Style','slider',...
           'Position',[25 285 240 20],...
           'units','normalized', ...
           'Value', amplB, ...
           'Min',0.1,'Max',1, ...
           'Value',1, ...
           'SliderStep',[0.05 0.1],...
           'Tag','SamplB',...
           'Callback',@sliderCallback);

%% GUI for slider, setting startphase of source A 

txtSliderPhaseA = uicontrol('Parent',figure1,...
           'Style','text',...
           'Position',[40 220 210 20],...
           'units','normalized', ...
           'String','Start-phase "Right":');
       
sliderPhaseA = uicontrol('Parent',figure1,...
           'Style','slider',...
           'Position',[25 195 240 20],...
           'units','normalized', ...
           'Value', phaseA, ...
           'Min',0,'Max',2*pi, ...
           'Value',0, ...
           'SliderStep',[0.0278 1],...
           'Tag','SphasA',...
           'Callback',@sliderCallback);

%% GUI for slider, setting startphase of source B 

txtSliderPhaseB = uicontrol('Parent',figure1,...
           'Style','text',...
           'Position',[40 130 210 20],...
           'units','normalized', ...
           'String','Start-phase "Left":');
       
sliderPhaseB = uicontrol('Parent',figure1,...
           'Style','slider',...
           'Position',[25 105 240 20],...
           'units','normalized', ...
           'Value', phaseB, ...
           'Min',0,'Max',2*pi, ...
           'Value',0, ...
           'SliderStep',[0.0278 1],...
           'Tag','SphasB',...
           'Callback',@sliderCallback);
%--------------------------
btn = uicontrol('Parent',figure1,...
           'Position',[500 20 200 60],...
           'units','normalized', ...
           'Style','pushbutton',...
           'String','Click mode',...
           'Tag','Button',...
           'Callback', 'stop(t); statusT = 0');%@sliderCallback);
       
       
 display = uicontrol('Parent',figure1,...
           'Style','edit',...
           'Position',[40 590 210 20],...
           'units','normalized', ...
           'String', '');
       
       
%-------------------------------------------------------------------------%

freqA=get(sliderFreqA,'Value');
freqB=get(sliderFreqB,'Value');
    
amplA=get(sliderAmplA,'Value');
amplB=get(sliderAmplB,'Value');
    
phaseA=get(sliderPhaseA,'Value');
phaseB=get(sliderPhaseB,'Value');
