function choice = InputDialog
global freqA
global freqB
global amplA
global amplB
global phaseA
global phaseB

    d = dialog('Position',[300 300 250 310],'Name','Source Parameter');

% GUI for slider, setting frequency of source A 
    txtSliderFreqA = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 280 210 20],...
           'String','Frequency A:');
       
    sliderFreqA = uicontrol('Parent',d,...
           'Style','slider',...
           'Position',[10 260 240 20],...
           'Value', freqA, ...
           'Min',3,'Max',30, ...
           'Value',15, ...
           'SliderStep',[0.1 0.5]);
       
       
% GUI for slider, setting frequency of source B 
    txtSliderFreqB = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 230 210 20],...
           'String','Frequency B:');
       
    sliderFreqB = uicontrol('Parent',d,...
           'Style','slider',...
           'Position',[10 210 240 20],...
           'Value', freqB, ...
           'Min',3,'Max',30, ...
           'Value',15, ...
           'SliderStep',[0.1 0.5]);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% GUI for slider, setting amplitude of source A 
    txtSliderAmplA = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 180 210 20],...
           'String','Amplitude A:');
       
    sliderAmplA = uicontrol('Parent',d,...
           'Style','slider',...
           'Position',[10 160 240 20],...
           'Value', amplA, ...
           'Min',0.1,'Max',1, ...
           'Value',1, ...
           'SliderStep',[0.05 0.1]);

% GUI for slider, setting amplitude of source B 
    txtSliderAmplB = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 140 210 20],...
           'String','Amplitude B:');
       
    sliderAmplB = uicontrol('Parent',d,...
           'Style','slider',...
           'Position',[10 120 240 20],...
           'Value', amplB, ...
           'Min',0.1,'Max',1, ...
           'Value',1, ...
           'SliderStep',[0.05 0.1]);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% GUI for slider, setting startphase of source A 
    txtSliderPhaseA = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 90 210 20],...
           'String','Start-phase A:');
       
    sliderPhaseA = uicontrol('Parent',d,...
           'Style','slider',...
           'Position',[10 70 240 20],...
           'Value', phaseA, ...
           'Min',0,'Max',360, ...
           'Value',0, ...
           'SliderStep',[1 1]);

% GUI for slider, setting startphase of source B 
    txtSliderPhaseB = uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 50 210 20],...
           'String','Start-phase B:');
       
    sliderPhaseB = uicontrol('Parent',d,...
           'Style','slider',...
           'Position',[10 30 240 20],...
           'Value', phaseB, ...
           'Min',0,'Max',360, ...
           'Value',0, ...
           'SliderStep',[1 1]);

%% Resume Button
% When parameters are set/defaults are chosen, user can resume  to waveplot
    resume = uicontrol('Parent',d,...
           'Position',[89 5 80 25],...
           'String','Use Values',...
           'Callback','uiresume(gcf)');

%% Getting the Values
% Wait for d to resume before running to completion at first run
if isempty(freqA) || isempty(freqB) || isempty(amplA) || isempty(amplB) || isempty(phaseA) || isempty(phaseB)
uiwait(d);
end
       
    freqA=get(sliderFreqA,'Value');
    freqB=get(sliderFreqB,'Value');
    
    amplA=get(sliderAmplA,'Value');
    amplB=get(sliderAmplB,'Value');
    
    phaseA=get(sliderPhaseA,'Value');
    phaseB=get(sliderPhaseB,'Value');
    
figure1.Visible = 'on';        % When user clicked resume, the other plot 
                               %is shown
    
end